url: http://edpoole.github.com
site_name: "Designer and Front-end Developer"
markdown: rdiscount
rdiscount:
    extensions: [smart]
pygments: true
permalink: /articles/:title
paginate_path: 'articles/:num'
paginate: 5
# baseurl: /